---
apiVersion: v1
kind: Service
metadata:
  name: flask
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: flask
  type: LoadBalancer


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
spec:
  replicas: 1
  selector:
   matchLabels:
    app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - image: jiajunngjj/flask-polling-app:0.1.70
        name: flask-app
        ports:
        - containerPort: 8080
      restartPolicy: "Always"
